version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: zoo
      POSTGRES_USER: zoo
      POSTGRES_PASSWORD: zoo
    ports:
      - "5432:5432"
    volumes:
      - zoo_pg:/var/lib/postgresql/data
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: zoo
      RABBITMQ_DEFAULT_PASS: zoo
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  zoo_pg:
